### ISSUE TITLE
Adding a Slideshow to Left or Right Column Should Not Generate Traceback in Plone 5

### ISSUE THREAD

**Issue by elizabethstratton** [collective/collective.easyslideshow#13]
Plone 5.0a3.dev0 (5002)

 * install easy slideshow
 * add folder called `slideshow-folder`
 * add multiple images
 * add page
 * title, save, publish
 * `More Options` > `Plone Leftcolumn` or `Plone Rightcolumn`
 * Add slideshow portlet from dropdown
 * Submit
 * Traceback occurs

{{{
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.app.portlets.browser.formhelper, line 59, in __call__
  Module z3c.form.form, line 218, in __call__
  Module plone.z3cform.fieldsets.extensible, line 58, in update
  Module plone.autoform.form, line 33, in updateFields
  Module plone.autoform.base, line 54, in updateFieldsFromSchemata
  Module plone.autoform.form, line 22, in schema
NotImplementedError: The class deriving from AutoExtensibleForm must have a 'schema' property
}}}

**Comment by cdw9** [comment]
This is now fixed in the plone5 branch, which will be the 3.0 release
